(ns noahtheduke.olympic-medals.data)

(def country-code->name
  {"AFG" "Afghanistan"
   "AGU" "Anguilla"
   "AHO" "Netherlands Antilles"
   "AIN" "Individual Neutral Athletes"
   "ALB" "Albania"
   "ALG" "Algeria"
   "AND" "Andorra"
   "ANG" "Angola"
   "ANT" "Antigua and Barbuda"
   "ANZ" "Australasia"
   "ARG" "Argentina"
   "ARM" "Armenia"
   "ARU" "Aruba"
   "ASA" "American Samoa"
   "AUS" "Australia"
   "AUT" "Austria"
   "AZE" "Azerbaijan"
   "BAH" "The Bahamas"
   "BAN" "Bangladesh"
   "BAR" "Barbados"
   "BDI" "Burundi"
   "BEL" "Belgium"
   "BEN" "Benin"
   "BER" "Bermuda"
   "BHU" "Bhutan"
   "BIH" "Bosnia and Herzegovina"
   "BIZ" "Belize"
   "BLR" "Belarus"
   "BOH" "Bohemia"
   "BOL" "Bolivia"
   "BOT" "Botswana"
   "BRA" "Brazil"
   "BRN" "Bahrain"
   "BRT" "Saint-Barthélemy"
   "BRU" "Brunei Darussalam"
   "BUL" "Bulgaria"
   "BUR" "Burkina Faso"
   "CAF" "Central African Republic"
   "CAM" "Cambodia"
   "CAN" "Canada"
   "CAY" "Cayman Islands"
   "CEA" "Central America"
   "CGO" "Congo"
   "CHA" "Chad"
   "CHI" "Chile"
   "CHN" "People's Republic of China"
   "CIV" "Côte d'Ivoire"
   "CKI" "Cocos Islands"
   "CMR" "Cameroon"
   "COD" "Democratic Republic of the Congo"
   "COK" "Cook Islands"
   "COL" "Colombia"
   "COM" "Comoros"
   "COR" "Korea Team"
   "CPV" "Cabo Verde"
   "CRC" "Costa Rica"
   "CRO" "Croatia"
   "CRT" "Crete"
   "CUB" "Cuba"
   "CUR" "Curaçao"
   "CYP" "Cyprus"
   "CZE" "Czechia"
   "DEN" "Denmark"
   "DJI" "Djibouti"
   "DMA" "Dominica"
   "DOM" "Dominican Republic"
   "ECU" "Ecuador"
   "EGY" "Egypt"
   "EOR" "Équipe Olympique des Réfugies"
   "ERI" "Eritrea"
   "ESA" "El Salvador"
   "ESP" "Spain"
   "EST" "Estonia"
   "ETH" "Ethiopia"
   "EUN" "Unified Team"
   "FAR" "Faroe Islands"
   "FGU" "French Guiana"
   "FIJ" "Fiji"
   "FIN" "Finland"
   "FLI" "Falkland Islands"
   "FPN" "French Polynesia"
   "FRA" "France"
   "FRG" "West Germany"
   "FSM" "Federated States of Micronesia"
   "GAB" "Gabon"
   "GAM" "The Gambia"
   "GBR" "Great Britain"
   "GBS" "Guinea Bissau"
   "GDP" "Guadeloupe"
   "GDR" "East Germany"
   "GEO" "Georgia"
   "GEQ" "Equatorial Guinea"
   "GER" "Germany"
   "GHA" "Ghana"
   "GIB" "Gibraltar"
   "GRE" "Greece"
   "GRL" "Greenland"
   "GRN" "Grenada"
   "GUA" "Guatemala"
   "GUE" "Guernsey"
   "GUI" "Guinea"
   "GUM" "Guam"
   "GUY" "Guyana"
   "HAI" "Haiti"
   "HEL" "St. Helena"
   "HKG" "Hong Kong, China"
   "HON" "Honduras"
   "HUN" "Hungary"
   "IFR" "International Federation Representative"
   "INA" "Indonesia"
   "IND" "India"
   "IOA" "Independent Olympic Athletes"
   "IOM" "Isle of Man"
   "IRI" "Islamic Republic of Iran"
   "IRL" "Ireland"
   "IRQ" "Iraq"
   "ISL" "Iceland"
   "ISR" "Israel"
   "ISV" "United States Virgin Islands"
   "ITA" "Italy"
   "IVB" "British Virgin Islands"
   "JAM" "Jamaica"
   "JER" "Jersey"
   "JOR" "Jordan"
   "JPN" "Japan"
   "KAZ" "Kazakhstan"
   "KEN" "Kenya"
   "KGZ" "Kyrgyzstan"
   "KIR" "Kiribati"
   "KOR" "Republic of Korea"
   "KOS" "Kosovo"
   "KSA" "Kingdom of Saudi Arabia"
   "KUW" "Kuwait"
   "LAO" "Lao People's Democratic Republic"
   "LAT" "Latvia"
   "LBA" "Libya"
   "LBN" "Lebanon"
   "LBR" "Liberia"
   "LCA" "Saint Lucia"
   "LES" "Lesotho"
   "LIE" "Liechtenstein"
   "LTU" "Lithuania"
   "LUX" "Luxembourg"
   "MAC" "Macau"
   "MAD" "Madagascar"
   "MAL" "Malaya"
   "MAR" "Morocco"
   "MAS" "Malaysia"
   "MAW" "Malawi"
   "MDA" "Republic of Moldova"
   "MDV" "Maldives"
   "MEX" "Mexico"
   "MGL" "Mongolia"
   "MHL" "Marshall Islands"
   "MIX" "Mixed team"
   "MKD" "North Macedonia"
   "MLI" "Mali"
   "MLT" "Malta"
   "MNE" "Montenegro"
   "MON" "Monaco"
   "MOZ" "Mozambique"
   "MQE" "Martinique"
   "MRI" "Mauritius"
   "MRT" "Saint-Martin"
   "MTN" "Mauritania"
   "MTS" "Montserrat"
   "MWI" "Midway Islands"
   "MYA" "Myanmar"
   "MYT" "Mayotte"
   "NAM" "Namibia"
   "NBO" "North Borneo"
   "NCA" "Nicaragua"
   "NCD" "New Caledonia"
   "NED" "Netherlands"
   "NEP" "Nepal"
   "NFI" "Norfolk Island"
   "NFL" "Newfoundland"
   "NGR" "Nigeria"
   "NIG" "Niger"
   "NIU" "Niue"
   "NMI" "Northern Mariana Islands"
   "NOR" "Norway"
   "NRU" "Nauru"
   "NZL" "New Zealand"
   "OMA" "Oman"
   "PAK" "Pakistan"
   "PAN" "Panama"
   "PAR" "Paraguay"
   "PER" "Peru"
   "PHI" "Philippines"
   "PLE" "Palestine"
   "PLW" "Palau"
   "PNG" "Papua New Guinea"
   "POL" "Poland"
   "POR" "Portugal"
   "PRK" "Democratic People's Republic of Korea"
   "PUR" "Puerto Rico"
   "QAT" "Qatar"
   "RHO" "Rhodesia"
   "RNN" "La Réunion"
   "ROC" "ROC"
   "ROU" "Romania"
   "RSA" "South Africa"
   "RUS" "Russian Federation"
   "RWA" "Rwanda"
   "SAA" "Saar"
   "SAM" "Samoa"
   "SCG" "Serbia and Montenegro"
   "SEN" "Senegal"
   "SEY" "Seychelles"
   "SGP" "Singapore"
   "SKN" "Saint Kitts and Nevis"
   "SLE" "Sierra Leone"
   "SLO" "Slovenia"
   "SMR" "San Marino"
   "SMT" "Sint Maarten"
   "SOL" "Solomon Islands"
   "SOM" "Somalia"
   "SPM" "St. Pierre and Miquelon"
   "SRB" "Serbia"
   "SRI" "Sri Lanka"
   "SSD" "South Sudan"
   "STP" "São Tomé and Príncipe"
   "SUD" "Sudan"
   "SUI" "Switzerland"
   "SUR" "Suriname"
   "SVB" "Svalbard"
   "SVK" "Slovakia"
   "SWE" "Sweden"
   "SWZ" "Eswatini"
   "SYR" "Syrian Arab Republic"
   "TAN" "United Republic of Tanzania"
   "TCH" "Czechoslovakia"
   "TGA" "Tonga"
   "THA" "Thailand"
   "TJK" "Tajikistan"
   "TKL" "Tokelau"
   "TKM" "Turkmenistan"
   "TKS" "Turks and Caicos Islands"
   "TLS" "Timor-Leste"
   "TOG" "Togo"
   "TPE" "Chinese Taipei"
   "TTO" "Trinidad and Tobago"
   "TUN" "Tunisia"
   "TUR" "Türkiye"
   "TUV" "Tuvalu"
   "UAE" "United Arab Emirates"
   "UAR" "United Arab Republic"
   "UGA" "Uganda"
   "UKR" "Ukraine"
   "UNK" "Unknown"
   "URS" "Soviet Union"
   "URU" "Uruguay"
   "USA" "United States"
   "UZB" "Uzbekistan"
   "VAN" "Vanuatu"
   "VAT" "Vatican City"
   "VEN" "Venezuela"
   "VIE" "Vietnam"
   "VIN" "Saint Vincent and the Grenadines"
   "VNM" "South Vietnam"
   "WAF" "Wallis and Futuna"
   "WIF" "West Indies Federation"
   "XMI" "Christmas Island"
   "YAR" "North Yemen"
   "YEM" "Yemen"
   "YMD" "South Yemen"
   "YUG" "Yugoslavia"
   "ZAM" "Zambia"
   "ZIM" "Zimbabwe"})

(def country-codes (set (keys country-code->name)))
(def country-names (set (vals country-code->name)))


(def season
  {["1896" "Athina"] "Summer"
   ["1900" "Paris"] "Summer"
   ["1904" "St. Louis"] "Summer"
   ["1906" "Athina"] "Intercalated"
   ["1908" "London"] "Summer"
   ["1912" "Stockholm"] "Summer"
   ["1916" "Berlin"] "Summer"
   ["1920" "Antwerpen"] "Summer"
   ["1924" "Chamonix"] "Winter"
   ["1924" "Paris"] "Summer"
   ["1928" "Amsterdam"] "Summer"
   ["1928" "Sankt Moritz"] "Winter"
   ["1932" "Lake Placid"] "Winter"
   ["1932" "Los Angeles"] "Summer"
   ["1936" "Berlin"] "Summer"
   ["1936" "Garmisch-Partenkirchen"] "Winter"
   ["1940" "Garmisch-Partenkirchen"] "Winter"
   ["1940" "Helsinki"] "Summer"
   ["1944" "Cortina d'Ampezzo"] "Winter"
   ["1944" "London"] "Summer"
   ["1948" "London"] "Summer"
   ["1948" "Sankt Moritz"] "Winter"
   ["1952" "Helsinki"] "Summer"
   ["1952" "Oslo"] "Winter"
   ["1956" "Cortina d'Ampezzo"] "Winter"
   ["1956" "Melbourne"] "Summer"
   ["1956" "Stockholm"] "Equestrian"
   ["1960" "Roma"] "Summer"
   ["1960" "Squaw Valley"] "Winter"
   ["1964" "Innsbruck"] "Winter"
   ["1964" "Tokyo"] "Summer"
   ["1968" "Ciudad de México"] "Summer"
   ["1968" "Grenoble"] "Winter"
   ["1972" "München"] "Summer"
   ["1972" "Sapporo"] "Winter"
   ["1976" "Innsbruck"] "Winter"
   ["1976" "Montréal"] "Summer"
   ["1980" "Lake Placid"] "Winter"
   ["1980" "Moskva"] "Summer"
   ["1984" "Los Angeles"] "Summer"
   ["1984" "Sarajevo"] "Winter"
   ["1988" "Calgary"] "Winter"
   ["1988" "Seoul"] "Summer"
   ["1992" "Albertville"] "Winter"
   ["1992" "Barcelona"] "Summer"
   ["1994" "Lillehammer"] "Winter"
   ["1996" "Atlanta"] "Summer"
   ["1998" "Nagano"] "Winter"
   ["2000" "Sydney"] "Summer"
   ["2002" "Salt Lake City"] "Winter"
   ["2004" "Athina"] "Summer"
   ["2006" "Torino"] "Winter"
   ["2008" "Beijing"] "Summer"
   ["2010" "Singapore"] "Summer Youth"
   ["2010" "Vancouver"] "Winter"
   ["2012" "Innsbruck"] "Winter Youth"
   ["2012" "London"] "Summer"
   ["2014" "Nanjing"] "Summer Youth"
   ["2014" "Sochi"] "Winter"
   ["2016" "Lillehammer"] "Winter Youth"
   ["2016" "Rio de Janeiro"] "Summer"
   ["2018" "Buenos Aires"] "Summer Youth"
   ["2018" "PyeongChang"] "Winter"
   ["2020" "Lausanne"] "Winter Youth"
   ["2020" "Tokyo"] "Summer"
   ["2022" "Beijing"] "Winter"
   ["2024" "Gangwon"] "Winter Youth"
   ["2024" "Paris"] "Summer"
   ["2026" "Dakar"] "Summer Youth"
   ["2026" "Milano-Cortina d'Ampezzo"] "Winter"
   ["2028" "Dolomiti Valtellina"] "Winter Youth"
   ["2028" "Los Angeles"] "Summer"
   ["2030" "French Alps"] "Winter"
   ["2032" "Brisbane"] "Summer"
   ["2034" "Salt Lake City, Utah"] "Winter"})
